version: '3'
services:
    tua-db:
        container_name: tua-db
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=tua0110aut
            - MYSQL_DATABASE=ssbd02local
            - MYSQL_USER=mySQL
            - MYSQL_PASSWORD=tua0110aut
        volumes:
            - tua01-volume:/var/lib/mysql
        networks:
            - "tua01-network"

    tua-wildfly:
        container_name: tua-wildfly
        build:
            context: ..
            dockerfile: docker/Dockerfile
        environment:
            - WILDFLY_PASSWORD=tua0110aut
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=8080
        networks:
            - "tua01-network"
        depends_on:
            - "tua-db"

    nginx-proxy:
        container_name: tua-nginx
        image: nginxproxy/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - "tua01-network"
        depends_on:
            - "tua-wildfly"

volumes:
    tua01-volume:

networks:
    tua01-network:


    
        
